language: node_js
node_js:
  - "6"
env:
  - CXX=g++-4.8
cache: yarn
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
script:
  -  lerna bootstrap
  -  lerna run test